In [1]:
import pandas as pd

In [2]:
import pandas as pd
df = pd.read_csv("shopping3.csv")
df["Revenue"] = df["UnitPrice"] * df["Quantity"]

df["OrderDate"] = pd.to_datetime(df["OrderDate"])
df["Month"] = df["OrderDate"].dt.month

In [3]:
pd.pivot_table( df, values="Revenue", index="Region", columns="Month",  aggfunc="sum", fill_value=0 )

Month,1,2,3,4,5,6,7,8,9,10,11,12
Region,,,,,,,,,,,,
Busan,377500.0,241600.0,51200.0,297700.0,400000.0,132400.0,132800.0,457400.0,310500.0,51700.0,317800.0,300000.0
Daegu,374700.0,458200.0,24000.0,462700.0,332400.0,329800.0,134500.0,417800.0,98900.0,49000.0,125800.0,237300.0
Daejeon,0.0,182400.0,126800.0,143000.0,153200.0,184800.0,493200.0,243700.0,4500.0,315700.0,126900.0,354900.0
Gwangju,61800.0,242600.0,102900.0,747900.0,357800.0,536000.0,169800.0,355200.0,455900.0,109300.0,73500.0,461000.0
Incheon,266000.0,280000.0,136700.0,55000.0,290700.0,35600.0,138400.0,171900.0,197500.0,102400.0,24000.0,276900.0
Seoul,79700.0,205500.0,167000.0,334000.0,150800.0,255700.0,479500.0,305600.0,301700.0,91700.0,267800.0,118600.0

In [4]:
pd.pivot_table( df, values="Quantity", index="Month", aggfunc="mean")

       Quantity
Month
1      1.750000
2      1.814815
3      1.500000
4      1.785714
5      1.575758
6      1.750000
7      1.740741
8      1.656250
9      1.500000
10     1.578947
11     1.285714
12     1.633333